draft_lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
from lab_1.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^$', index)
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_7/urls.py
from django.conf.urls import url
from .views import index, add_friend, validate_npm, delete_friend, friend_list, friend_list_json

urlpatterns = [
     url(r'^$', index, name='index'),
     url(r'^add-friend/$', add_friend, name='add-friend'),
     url(r'^validate-npm/$', validate_npm, name='validate-npm'),
     url(r'delete-friend/(?P<npm>[0-9]+)/$', delete_friend, name='delete-friend'),
     url(r'^get-friend-list/$', friend_list_json, name='get-friend-list'),
     url(r'^friend-list/$', friend_list, name='friend-list')
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_3.urls as lab_3
import lab_2_addon.urls as lab_2_addon
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
from lab_1.views import index as index_lab1
from django.views.generic import RedirectView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^lab-2/', include(lab_2,namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon,namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')), 
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^$', RedirectView.as_view(permanent=True, url='/lab-2/')),
]

lab_7/models.py
from __future__ import unicode_literals
from django.db import models

class Friend(models.Model):
    friend_name = models.CharField(max_length=400)
    npm = models.CharField(max_length=250)
    added_at = models.DateField(auto_now_add=True)

    def as_dict(self):
    	return {
    		"friend_name": self.friend_name,
    		"npm": self.npm,
    	}

lab_7/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.core import serializers
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Friend
from .api_csui_helper.csui_helper import CSUIhelper
import os
import json

response = {}
csui_helper = CSUIhelper()

def index(request):
    mahasiswa_list = csui_helper.instance.get_mahasiswa_list()
    friend_list = Friend.objects.all()

    # this will assume, if no page selected, it is on the first page
    page = request.GET.get('page', 1)
    paginate_data = paginate_page(page, mahasiswa_list)
    mahasiswa = paginate_data['data']
    page_range = paginate_data['page_range']

    response = {"mahasiswa_list": mahasiswa, "friend_list": friend_list, "page_range": page_range}
    html = 'lab_7/lab_7.html'
    return render(request, html, response)

def paginate_page(page, lst):
    paginator = Paginator(lst, 10)

    # assign data value with page
    try:
        data = paginator.page(page)
    except PageNotAnInteger:
        data = paginator.page(1)
    except EmptyPage:
        data = paginator.page(paginator.num_pages)

    # index of curr page
    index_now = data.number - 1

    # max index of your pages, last page - 1
    max_index = len(paginator.page_range) #page_range returns an iterator

    # get start and last index for each slices/pages of the lst
    start_index = index_now if index_now >= 10 else 0
    end_index = 10 if index_now > max_index - 10 else max_index

    # get out new page_range thus pass it to list to make our slice possible again
    page_range = list(paginator.page_range)[start_index:end_index]

    paginate_data = {'data':data, 'page_range':page_range}
    return paginate_data

def friend_list(request):
    html = 'lab_7/daftar_teman.html'
    return render(request, html, response)

def friend_list_json(request):
    friends = [obj.as_dict() for obj in Friend.objects.all()]
    return JsonResponse({"results": friends}, content_type='application/json')

@csrf_exempt
def add_friend(request):
    if request.method == 'POST':
        name = request.POST['name']
        npm = request.POST['npm']
        isAdaFriend = Friend.objects.filter(npm=npm).exists()
        if not isAdaFriend:
            friend = Friend(friend_name=name, npm=npm)
            friend.save()
        data = model_to_dict(friend)
        print(friend)
        return HttpResponse(data)

def delete_friend(request, npm):
    Friend.objects.filter(npm=npm).delete()
    return HttpResponseRedirect('/lab-7/friend-list')

@csrf_exempt
def validate_npm(request):
    npm = request.POST.get('npm', None)
    data = {
        'is_taken': (Friend.objects.filter(npm=npm).exists()), #lakukan pengecekan apakah Friend dgn npm tsb sudah ada
    }
    return JsonResponse(data)

# 
def model_to_dict(obj):
    data = serializers.serialize('json', [obj,]) #
    struct = json.loads(data)
    data = json.dumps(struct[0]["fields"])
    return data

lab_7/templates/lab_7/daftar_teman.html
{% extends "lab_7/layout/base.html" %}

{% block content %}
    <section name="friend-list">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-lg-8">
                    <h2> Friend Fasilkom</h2>
                    <div id="friend-list" class="list-group">

                    </div>
                </div>
                
            </div>
        </div>
    </section>
{% endblock %}
{% block javascript %}
    <script>
        $( document ).ready(function () {
            // mengambil daftar teman yang ada di database
            $.ajax({
                method: "GET",

                // mengambil 'data' yang ada di url tersebut
                url: "{% url 'lab-7:get-friend-list' %}",

                // menampilkan 'data' yang berhasil diambil dan diberi nama 'friend_list'
                success: function (friend_list) {
                    console.log(friend_list); 

                    // untuk setiap elemen di lst, yaitu 'friend', yang posisinya ditunjukkan dengan 'index'
                    $.each(friend_list.results, function(index, friend) {
                        var del_button = '<span class="pull-right"><button type="button" class="btn btn-xs btn-danger"' + 'onClick="deleteFriend(\'' + friend.npm + '\')"> HAPUS </span></button>';
                        var input = "<a class='list-group-item clearfix'>" + friend.friend_name + " (" + friend.npm  + ")" + del_button + "</a>";
                        $('#friend-list').append(input);
                    });
                },
                error: function(error){
                    // #tampilkan pesan error
                    var errorMsg = '<div class alert alert-danger>\
                        <strong>Oops!</strong> Tidak ada teman\
                        </div>';
                    $('#friend-list').append(errorMsg);
                }
            });   
        });
        const deleteFriend = function(npm) {
            window.open('delete-friend/' + npm + '/', '_self');
        }
    </script>
{% endblock %}

lab_7/templates/lab_7/lab_7.html
{% extends "lab_7/layout/base.html" %}
{% block content %}
<section name="mahasiswa-list" id="mahasiswa-list">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-lg-8">
                <h2> Mahasiswa Fasilkom</h2>
                <div class="list-group">
                    {% if mahasiswa_list %}
                        {% for mahasiswa in mahasiswa_list %}
                            <a class="list-group-item clearfix">
                                {{ mahasiswa.nama }} ({{ mahasiswa.npm }})
                                <span class="pull-right">
                        <span class="btn btn-xs btn-default" onClick="addFriend('{{ mahasiswa.nama }}', '{{ mahasiswa.npm }}')">
                            Tambah sebagai teman
                        </span>
                    </span>
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada mahasiswa
                        </div>
                    {% endif %}
                </div>
                <div id="paginate">
                    {% if mahasiswa_list.has_other_pages %}
                        <ul class="pagination">
                            {% if mahasiswa_list.has_previous %}
                                <li><a href="{% url 'lab-7:index' %}">&laquo;</a></li>
                                <li><a href="?page={{ mahasiswa_list.previous_page_number }}">&lsaquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&lsaquo;</span></li>
                            {% endif %}
        
                            {% for page_number in page_range %}
                                {% if mahasiswa_list.number == page_number %}
                                    <li class="active"><span>{{ page_number }}</span></li>
                                {% else %}
                                    <li><a href="?page={{ page_number }}">{{ page_number }}</a></li>
                                {% endif %}
                            {% endfor %}
                            
                            {% if mahasiswa_list.has_next %}
                                <li><a href="?page={{ mahasiswa_list.next_page_number }}">&rsaquo;</a></li>
                                <li><a href="?page={{ mahasiswa_list.paginator.num_pages }}">&raquo;</a></li>
                            {% else %}
                                <li class="disabled"><span>&raquo;</span></li>
                            {% endif %}
                        </ul>
                    {% endif %}
                </div>
            </div>
            <div class="col-lg-4">
                <h2> Teman Saya </h2>
                <div class="list-group" id="friend-list">
                    {% if friend_list %}
                        {% for friend in friend_list %}
                            <a class="list-group-item clearfix">
                                {{ friend.friend_name }} ({{ friend.npm }})
                            </a>
                        {% endfor %}
                    {% else %}
                        <div class="alert alert-danger text-center">
                            <strong>Opps!</strong> Tidak ada teman
                        </div>
                    {% endif %}
                </div>
                <form id="add-friend" action="#">
                    {% csrf_token %}
                    <label for="field_npm">npm</label>
                    <input id="field_npm" type="text" name="npm" class="form-control"/>
                    <label for="field_name">name</label>
                    <input id="field_name" type="text" name="name" class="form-control"/>
                    <button type="submit">Tambah</button>
                </form>
            </div>
        </div>
    </div>
</section>
{% endblock %}
{% block javascript %}
<script>
    var addFriend = function(nama, npm) {
        $.ajax({
            method: "POST", // melakukan method POST
            url: "{% url 'lab-7:add-friend' %}", // di url berikut
            data: { name: nama, npm: npm}, // mengambil data berikut
            dataType : 'json',
            success : function (friend) {
                html = '<a class="list-group-item clearfix">' +
                    friend.friend_name + ' (' + npm + ')' + 
                    '</a>';
                $("#friend-list").append(html)
            },
            error : function (error) {
                alert("Mahasiswa tersebut sudah ditambahkan sebagai teman")
            }
        });
    };

    // menambahkan teman ketika tombol submit ditekan
    $("#add-friend").on("submit", function () {
       name = $("#field_name").val()
       npm = $("#field_npm").val()
        addFriend(name, npm)
        event.preventDefault(); // default action of the event will not be triggered 
    });

    
    $("#field_npm").change(function () {
        console.log( $(this).val() );
        npm = $(this).val();
        $.ajax({
            method: "POST",
            url: '{% url "lab-7:validate-npm" %}',
            data: {
                'npm': npm
            },
            dataType: 'json',
            success: function (data) {
                console.log(data)
                if (data.is_taken) {
                    alert("Mahasiswa dengan npm seperti ini sudah ada");
                }
            }
        });
    });

/*
 * A plugin for making Bootstrap's pagination more responsive
 * https://github.com/auxiliary/rpage/blob/master/responsive-paginate.jss
*/

(function ($){
    jQuery.fn.rPage = function () {
        var $this = $(this);
        for(var i = 0, max = $this.length; i < max; i++)
        {
            new rPage($($this[i]));
        }

        function rPage($container)
        {
            this.label = function()
            {
                var active_index = this.els.filter(".active").index();
                var rp = this;
                this.els.each(function(){
                    if (rp.isNextOrPrevLink($(this)) == false)
                    {
                        $(this).addClass("page-away-" + (Math.abs(active_index - $(this).index())).toString());
                    }
                    else
                    {
                        if ($(this).index() > active_index)
                        {
                            $(this).addClass("right-etc");
                        }
                        else
                        {
                            $(this).addClass("left-etc");
                        }
                    }
                });
            }

            this.makeResponsive = function()
            {
                this.reset();
                var width = this.calculateWidth();

                while (width > this.els.parent().parent().outerWidth() - 10)
                {
                    var did_remove = this.removeOne();
                    if (did_remove == false)
                    {
                        break;
                    }
                    width = this.calculateWidth();
                }
            }

            this.isNextOrPrevLink = function(element)
            {
                return (
                    element.hasClass('pagination-prev')
                    || element.hasClass('pagination-next')
                    || element.text() == "»"
                    || element.text() == "«"
                );
            }

            this.isRemovable = function(element)
            {
                if (this.isNextOrPrevLink(element))
                {
                    return false;
                }
                var index = this.els.filter(element).index();
                if (index == 1 || this.isNextOrPrevLink($container.find("li").eq(index + 1)))
                {
                    return false;
                }
                if (element.text() == "...")
                {
                    return false;
                }
                return true;
            }

            this.removeOne = function()
            {
                var active_index = this.els.filter(".active").index();
                var farthest_index = $container.find("li").length - 1;
                var next = active_index + 1;
                var prev = active_index - 1;

                for (var i = farthest_index - 1; i > 0; i--)
                {
                    var candidates = this.els.filter(".page-away-" + i.toString());
                    var candidate = candidates.filter(function(){
                        return this.style["display"] != "none";
                    });
                    if (candidate.length > 0)
                    {
                        for (var j = 0; j < candidate.length; j++)
                        {
                            var candid_candidate = candidate.eq(j);
                            if (this.isRemovable(candid_candidate))
                            {
                                candid_candidate.css("display", "none");
                                if (this.needsEtcSign(active_index, farthest_index - 1))
                                {
                                    this.els.eq(farthest_index - 2).before("<li class='disabled removable'><span>...</span></li>");
                                }
                                if (this.needsEtcSign(1, active_index))
                                {
                                    this.els.eq(1).after("<li class='disabled removable'><span>...</span></li>");
                                }
                                return true;
                            }
                        }
                    }
                }
                return false;
            }

            this.needsEtcSign = function(el1_index, el2_index)
            {
                if (el2_index - el1_index <= 1)
                {
                    return false;
                }
                else
                {
                    var hasEtcSign = false;
                    var hasHiddenElement = false;
                    for (var i = el1_index + 1; i < el2_index; i++)
                    {
                        var el = $container.find("li").eq(i);
                        if (el.css("display") == "none")
                        {
                            hasHiddenElement = true;
                        }
                        if (el.text() == "...")
                        {
                            hasEtcSign = true;
                        }
                    }
                    if (hasHiddenElement == true && hasEtcSign == false)
                    {
                        return true;
                    }
                }
                return false;
            }

            this.reset = function()
            {
                for (var i = 0; i < this.els.length; i++)
                {
                    this.els.eq(i).css("display", "inline");
                }
                $container.find("li").filter(".removable").remove();
            }

            this.calculateWidth = function()
            {
                var width = 0;
                for (var i = 0; i < $container.find("li").length; i++)
                {
              width += $container.find("li").eq(i).children("a").length
                && $container.find("li").eq(i).children("a").eq(0).outerWidth();
              width += $container.find("li").eq(i).children("span").length
                && $container.find("li").eq(i).children("span").eq(0).outerWidth();
                }
                return width;
            }

            this.els = $container.find("li");
            this.label();
            this.makeResponsive();

            var resize_timer;

            $(window).resize(
                $.proxy(function()
                {
                    clearTimeout(resize_timer);
                    resize_timer = setTimeout($.proxy(function(){this.makeResponsive()}, this), 100);
                }, this)
            );
        }
    };
}(jQuery));

$(document).ready(function () {
    $(".pagination").rPage();
});
</script>
{% endblock %}